- objects/functions.php
- objects/video.php
- view/mini-upload-form/upload.php
- view/mini-upload-form/videoEncoder.php
Add command line interface to upload videos. Use php -f upload.php -- -h in `view/mini-upload-form` for instructions. 
The -g parameter takes a comma-separated list of *NUMERICAL* groups (group IDs, actually) as argument, this due to the current absence of an easy way to get groups by their name, this can be changed when such has been implemented. I have not done this yet as there are things of higher concern, eg. the *abundance of SQL injection opportunities* in the code...).
```
Use: php -f upload.php -u <user> -f <file> [-d <description>] [-g "group1[,group2]] [-c] [-h]
-u user     valid username
-f file     input filename
-d descr    description
-g group(s) comma-separated numerical groups for which this item will be visible,
item will be public if this is left out
-c          copy …
```
> Add command line interface to upload videos

- .htaccess
- install/database.sql
- objects/video.php
- objects/videoRotate.json.php
- view/bootstrap/css/bootstrap.css
- view/css/player.css
- view/include/video.php
- view/js/video.js/video-js.css
- view/js/videojs-rotatezoom/videojs.zoomrotate.js
- view/managerVideos.php
- view/mini-upload-form/videoEncoder.php
- view/modeGallery.php
- view/modeYoutube.php
- view/videoEmbeded.php
Add video rotate command. This command does NOT rotate or reencode the video, it just changes the way the video is played in the (html5 - does not work in flash) web player. Two new columns in the videos table (rotation and zoom) indicate the way the video is to be presented to the user (zoom is not user-accessible just now). Two new buttons (rotate left and rotate right) are added to the video manager to facilitate rotation.
> Add video rotate command

- view/mini-upload-form/upload.php
the direct upload allows only .mp4-files. i'm not shure if the name-length is prechecked, but you do this anywhere on filetype-check (if mp4).
if the check is after the substring, it would be possible to fail there - so in some (anyway unallowed) cases, this could cause a unproper fail - but at all, this change would save work and make it less ugly.
btw-offtopic: nice sort-changes in next-list! would be really cool, when next video stays in category..
> remove .mp4 in name on upload

- view/js/script.js
Found the problem.
File: view/js/script.js - Row 149
Replaced: "player.updateSrc(srcs);"
To: "player.src(srcs);"
Now it's working.
> Fix for #408 - videos with ad not playing

- objects/listFiles.json.php
Hi Daniel,
Just find a display issue to  direct upload my local files. 
It looks like utf8_encode  only did convertion from  iso8599-1  to UTF8.  
change to use  mbstring_convert_encoding  which   convert from mb_internal_encoding to UTF8. which is more friendly to non-latin locals.
> bugfix - display non-latin filenames correctly in DirectUpload page

- plugin/SlackBot/SlackBot.php
This plugin is meant to communicate to a slack workspace as a bot.  It requires a special bot_user_oauth_access_token that can be generated in your slack workspace, with the required scopes.
This plugin iterates through the users who have subscribed to the current user’s channel.  On each iteration it takes the email from the subscribed user, and sends it to slack to look for a user id.  Then it takes the user id and uses it to send a message to the user via the slack bot channel in slack.
This plugin uses the users:read, and users:read:email scope to retrieve retrieve the slack id for the user.
> Created Slackbot Plugin

- view/xsendfile.php
Without this each download is marked a 'text/html', and downloaded as such. On my Mac that's not a problem, but when I download a file on an Android tablet, the resulting file is marked as a HTML file instead of as a video - and opening it will display a bunch of gibberish unicode instead of the video. This change includes the mime-type in each response, since (as far as I'm aware) there are no downsides to doing that.
> Always include 'content-type' header

- objects/functions.php
@DanielnetoDotCom PLEASE TAKE 5mn TO READ , Do NOT accept the pull request before correcting it .
First , I have really low knowledge of php . I managed to make the script work , but you will have to make it work properly .
The output of the sitemap looks like this for each video , in this way google will have accurate data of each element to crawl .
```
<url>
<loc>http://192.168.0.170/AVideo/video/529/eg-vs-vg-incredible-game-hype-chongqing-major-dota-2?channelName=NoobFromUA</loc>
<video:video>
<video:thumbnail_loc>http://192.168.0.170/AVideo/videos/_YPTuniqid_5e343e18303ef2.90675523.jpg</video:thumbnail_loc>
<video:title>EG vs VG - INCREDIBLE GAME HYPE! - CHONGQING MAJOR DOTA 2</video:title>
<video:description>Commentary by TobiWan &amp; Kyle  , this is just a description …
```
> Complete sitemap for google . SEO improve

- plugin/TheaterButton/addButton.js
The initial text was still `Theater` in compressed mode now it will start with `Default view`.
Changed also location the to be more in line with other video players. It also detects if the pip button is active as FF has no active pip button. 
- FireFox
And with Chrome it is also on the correct location.
- Chrome
- Example previous
> Fixed text and location

- plugin/TheaterButton/style.css
The theater icon was to large compared with the other icons. Fixed the sizing.
- Old:
- New:
> Theater icon made to same size as other icons

- plugin/YouPHPFlix2/view/modeFlixBody.php
When displaying the sorted by date row it should start with the newest video.
Andreas
> NetFlix plugin: descending sort in date

- .htaccess
If you try run AVideo on apache 2.4, you will receive 500 server error immediately, since 2.4 dont know anything about 'Order allow, deny' derictive. To fix that need to check if its apache 2.2 or 2.4
> Apache 2.4 fix, add <IfModule> to check if its apache2.2 or 2.4

- install/database.sql
- Email fields must be maxlenght 254 according to RFC https://www.ietf.org/rfc/rfc2821.txt
- I strongly recommend use always the same naming convention with the fields names: Always in lower case with "_" for split words. MySQL and linux system are case sensitive and tables and fields are files in linux...
> Small database improvements.

- objects/getTotalTodayAsync.php
*Refer: https://github.com/WWBN/AVideo/issues/4203*
> Hi there,
>
> I am seeing the following error in my avideo.log
> PHP Fatal error: Uncaught Error: Call to undefined method Video::getTotalToday() in 
> /var/www/html/objects/getTotalTodayAsync.php:13
>
> Is this something i can ignore?
>
> thanks
The error message seems to be generated via `getTotalLastDaysAsync.php`:
```PHP
$total = Video::getTotalToday($video_id);
```
AFAICT, the method `getTotalToday` seems to be defined by `video_statistic.php`:
```PHP
static function getTotalToday($video_id, $hour = 0, $returnArray = array()) {
```
But, the class which `getTotalToday` belongs to seems to be named as `VideoStatistic`, not `Video`:
```PHP
class VideoStatistic extends ObjectYPT {
```
Theoretically, this PR should fix the problem. …
> Bug-fix (#4203).

- view/about.php
This applies only on the standard `About Page`, as the `Customizer` plugin can replace the whole content of this page.
> About Page: Allow translation of strings

- view/js/tinymce/langs/sa.js
Sorry, the `sa` language pack for TinyMCE was erroneous, the language code in the file was left to `ar` code, which is incorrect in the AVideo context. This PR fixes that.
> TinyMCE: Fixing sa language pack

- objects/getImageFromFilenameAsync.php
@akhilleusuggo I noticed the cited issues earlier today. Requesting your feedback/review. :-) 
I haven't yet looked more deeply into the inner workings of `getImageFromFilenameAsync.php`, but since the responses at the issues seem to describe the warnings generated as not being too serious, more primarily a cosmetic concern (e.g., maybe users don't like seeing the warnings, but it doesn't affect the overall functionality of AVideo, and the particular functionality in question needs to eventually be reworked anyway), the changes proposed by this PR should resolve those "cosmetic concerns" (effectively, just suppressing the warnings by way of introducing a temporary error handler which does nothing with those warnings/errors at the affected lines), and without imposing any further more …
> Fix for #4272, #4211

- objects/configurationUpdate.json.php
- objects/emailAllUsers.json.php
- objects/functions.php
- objects/include_config.php
- objects/include_phpmailer.php
- objects/login.json.php
- objects/notifySubscribers.json.php
- objects/sendEmail.json.php
- objects/user.php
- objects/userRecoverPass.php
- objects/video.php
- objects/youtubeUpload.json.php
- plugin/ReportVideo/ReportVideo.php
- plugin/YPTWallet/YPTWallet.php
Since we already have Composer integration and dependencies properly mapped to the Composer autoloader, it may be slightly easier and cleaner for future maintainability to use the Composer autoloader instead of manual loading those particular dependencies (when possible, and only referring here to the dependencies mentioned in the `composer.json` file, of course).
This PR implements that (plus a little minor refactoring at the affected files).
This should also resolve (in a slightly better manner) the PHPMailer problems reported a few days ago (replacing the need for the `include_phpmailer.php` file).
> Use Composer autoloader instead of manual loading (when possible).

- plugin/Permissions/Permissions.php
- view/managerPlugins_body.php
When the **Permissions Plugin** tables aren't installed, the UI isn't working properly. Indeed, when the `users_groups_permissions` table is missing, all the actions made in the screen aren't taken into account. This is really confusing for the end-user.
Now, the `User Groups Permissions` is disabled in the `Plugins` page:
In the `Groups` page, all the buttons are disabled and a message is shown:
> Permissions Plugin: Disabling UI buttons when the plugin is not installed

- install/database.sql
- locale/fr.php
- objects/aVideoEncoder.json.php
- objects/video.php
- updatedb/updateDb.v9.8.sql
- view/managerVideos_body.php
This is for the progressiveUpload option of Avideo-Encoder, where the
encoded videos are sent as soon as they are encoded, and not in a
final batch. The video is immediatly avaiable but we need to display
that more encoded videos are to come.
> Add active and encoding status

- install/index.php
This is sometimes useful for local development.
> Allow the use of a blank database password during installation

- .github/workflows/validate.yml
Adds some basic linting to the workflow. This should help a little for being able to quickly identify whenever future commits introduce syntax errors in any of the PHP files checked, by changing the green "✔️" seen against commits in the commit history into a red "❌" for any future commits introducing such syntax errors.
Currently just checks `feed`, `install`, `locale`, `view`, and `index.php`. Because those directories (and one file) don't total too many files, checking just those shouldn't take too much time (based on the commit which this PR includes, approximately ~28 seconds).
But, because the `objects` and `plugin` directories contain a huge number of files, checking them at each commit would take a much longer amount of time (too much time, IMO), so better to just skip those for …
> Add PHP Linter.

- objects/user.php
Found a issue that sending two verification mail when user sign or when user try to connect with unverified mail and the server send new verification mail.
It already have a if statement to avoid sending multiple mail for 30 minute but the if statement is incorect.
We need to stop (return true) in the if statement if the difference between actual time and last send mail is less than 1800 and not more than.
When user try to loggin, the loginFromRequest() of objects/user.php execute "$user->login()" twice cause of "if ($response !== self::USER_LOGGED) {" statement at the same second.
That the difference between two call are less than 1800 second and we need to stop the execution of sendVerificationLink function.
> change > to < in already send mail if statement

- .github/workflows/docker-image.yml
- .github/workflows/validate.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- README.md
Given that the current latest AVideo tag is already at 11.6, it doesn't make sense to include empty roadmap entries for 8.x versions.
> Remove obsolete README.md data.

- plugin/API/API.php
Usage within the methods seems to be as an array, rather than as a string.
> Fix docblock comment param description.

- objects/listFiles.json.php
This fix will take the same allowed list to be considered in it's current original case (can be mixed), lower case format and also upper case format. Since it is also possible that some formats are mixed case (Ex: Mov instead of MOV) it is better to take all three cases (though may have duplicates in $fileStr, does not hurt.).
> Files with UPPER case extensions not listing in bulk upload

- plugin/YPTWallet/view/transferFunds.php
YPTWallet transfer funds from your account to another user account captcha text not submitted for non-admins
https://demo.avideo.com/plugin/YPTWallet/view/transferFunds.php
due to wrong css selector
https://github.com/WWBN/AVideo/blob/5fd3017d6aa0b2decd2863ffa66615a901b37e87/plugin/YPTWallet/view/transferFunds.php#L124
which should be the same as
https://github.com/WWBN/AVideo/blob/5fd3017d6aa0b2decd2863ffa66615a901b37e87/plugin/CustomizeUser/actionButton.php#L127
> Fixed captcha text css selector

- .github/workflows/depsreview.yaml
- .github/workflows/docker-image.yml
Limits some workflows to the parent repository, as they aren't needed at forks (don't need forks to be trying to generate docker images).
> Limit some workflows to the parent repository

- locale/en_AU.php
- locale/en_CA.php
Canadian English has similarities to American English, British English, and Australian English, but *is* just *slightly* different from all of them, so there may be value in providing support for it.
For example:
American English | British English and Australian English | Canadian English
---|---|---
Color | Colour | Colour
Colorize | Colourise | Colourize
Authorization | Authorisation | Authorization
Honorable | Honourable | Honourable
This pull request adds a locale file for it.
> Add Canadian English support + update Australian English.

- install/index.php
As shown in issue https://github.com/WWBN/AVideo/issues/9892 missing PHP module can cause breakage without error being reported. It seems desirable to check for their presence at installation time, which is what is change does.
> Add installation tests for required PHP modules

- objects/functions.php
Also improve Linux way of reading /etc/timezone, using file_get_contents() instead of forking a shell.
> Portable timezone read
