WWBN/AVideo

index.php

This patch:
- Subtle HTML/CSS beautification/normalisation.
- Fixes a few small typos.
- Removes excess trailing whitespace at EoL.
Possible further future improvements/recommendations:
- Move CSS into its own file (large inline CSS snippets could increase bandwidth usage and loading time slightly; moving the currently included inline CSS into its own file and referencing it via a stylesheet link as per the example set by the bootstrap CSS could resolve this).
- Implement templating and improve SoC (Separation of Concerns).

index.php patch.

---

.gitignore
install/FinishedProgressSample.mp4.txt
install/FinishedProgressSample.webm.txt
install/checkConfiguration.php
install/index.php
objects/include_config.php
view/css/main.css
view/include/navbar.php
view/include/video.php
view/mini-upload-form/videoEncoder.php

I adjusted the header elements position and style to use CSS Flexbox, as it is more 'stable' than inline-block and float strategy. Also, I have changed the footer color to be more smooth with the overall layout color.

Bypassing unecessary Enconding, Allow MySQL other than the default 3306 port connection, CSS Flexbox in the header and new style in the Footer

---

plugin/Gallery/view/modeGallery.php

i don't know if something speak against this change, but for me it's perfect, since the following videos are match the topic (based on category) much better. autoplay is really cool now (at least for what i except).

use catergorys, better match

---

view/css/custom/default.css

The right sidebar CSS modification

The right sidebar CSS modification

---

objects/video.php
plugin/Gallery/Gallery.php
plugin/Gallery/view/modeGallery.php
plugin/YouPHPFlix/YouPHPFlix.php
plugin/YouPHPFlix/view/firstPage.php
view/js/script.js

like descripted in the last PR;
- litedesign reworked
- litegallery implemented
- add cat to youphpflix (besider views and likes, when hover a video)
- optionalise of most- watched popular and newest-cat's. enabled by default, disable when wanted.
- optimised sql-traffic in compare to last litedesign
looks like it is more or less "bug-free", at least i didn't reconize bad effects..
i will do the unstable-branch when i've further ideas, so should stay stable :)

updated options/designs

---

.gitignore
Dockerfile
docker/000-default.conf

This PR adds a Dockerfile and according configuration files allowing users to build Docker containers for the encoder application.
This is part of DanielnetoDotCom/YouPHPTube#362.

Docker configuration

---

plugin/Live/index.php

adding related to the translation.

Update live index.php

---

objects/video.php

fix ugly prepared-statement-bug

---

objects/mysql_dal.php

some logical fixes for mysql_dal.php

pr-bugfixes

---

objects/category.php
objects/mysql_dal.php

i don't know why this appears now and not earlier.. confusing..

solve #711

---

view/managerUsers.php

fix for canStream and canUpload similar to #717

toggles beign set back

---

objects/user.php
view/include/head.php

#757 Fixed and object is destroyed to avoid memory consuption... 
Quotes unedded deleted.

Fix overwriting of object user, because is used with no scope

---

objects/Object.php

I was getting ugly warning due obligatory first parameter for the constructor, so I added default value to avoid it.

Added default parameter to constructor 

---

objects/userCreate.json.php
plugin/CustomizeAdvanced/CustomizeAdvanced.php

A new varibale is creatd at customized advanced and then validated at  userCreate.json  if sending autmatic mai is required.
If required, send it.

Adding capabitilies to send automatically verification login at signup

---

view/user.php

Hi!
Thanks for your great creation! It helps much for my children & myself.
Here are some fixes about home/login/signUp page problem caused by  'relative include' , when deployed with nginx & simple-php-router. 
HTH
Frank

simple-php-router - fix issue caused by relatively include in view/user.php

---

ansible-playbook

Works in debian9.x
No parameters yet

ansible plybook for youphptube

---

youphptube.yaml

Translate tasks in english, fixed issue with apache2.conf
After command ansible-playbook youphptube.yaml
Just go to http://IP/YouPHPTube/install
http://IP//YouPHPTube-Encoder/install
password for users created in mariadb are passw0rd. If you want other password ust tipit on mysql_user, password directive

Translate task in english, fixed issue with apache2.con

---

view/managerVideos.php

https://github.com/DanielnetoDotCom/YouPHPTube/commit/3cee2542fdcd8796f967de88ba1f88fe52cbf8d4#diff-6bf6022a99ea90672b499f9158e726a9R221

Hide sensitive info

---

objects/functions.php
objects/video.php

Hello,
It looks like there is a lot of edits to this file but it being caused by my autoformatter. If you reject it because of that I suppose that is fine. I can't figure out how to make the formatter jive with the style you have. Anyway this is a simple change, what it does is render the thumbnail as a letter box if the aspect ratio is something other than 16:9. This pull request compliments my other one for the encoder published today.

This commit sets thumbnails to letterboxed if they are portrait or sme other aspect that is not 16:9

---

plugin/SlackNotify/SlackNotify.php

Seems the plugin failed to merge before :/

SlackNotify Plugin 

---

view/modeYoutube.php

https://github.com/DanielnetoDotCom/YouPHPTube/issues/1456

Embed code improvement

---

Dockerfile

Without it the Dockerfile doesn't build

Add missing libzip dependency

---

plugin/MaintenanceMode/MaintenanceMode.php
plugin/MaintenanceMode/index.php

Added ability to use a discord url on the maintenancemode plugin

Add Discord to MainenanceMode plugin

---

plugin/CookieAlert/cookiealert-standalone.js
plugin/CookieAlert/cookiealert.css

Added the creator who made the cookie alert.

Added the creator of cookie alert

---

view/include/social.php

After the redesign of the Twitter page, the social button changed.

Update Twitter Button

---

plugin/DiscordNotify/DiscordNotify.php

Tested 2 times and both times the plugin worked correctly

Fix DiscordNotify Plugin

---

feed/index.php

https://github.com/WWBN/AVideo/issues/3035

Fix RSS title

---

objects/video.php
objects/videoSwap.json.php

Small fix as $line is not declared and i assume __LINE__ was expected.
Fixing error: ` PHP Notice:  Undefined variable: line in /var/www/test.somewhere.nl/objects/video.php on line 1140`

Fixed a variable in video.php and a fix to allow swapping of video files.

---

plugin/TheaterButton/addButton.js

missed a bracket

---

view/configurations_body.php

The language option with open text field is now a closed setting populated with a list based on the available files in the /locale.

Changed textfield to predefined pulldown

---

.gitignore
composer.json

The idea is that the project includes a composer file for managing external dependencies

Add basic composer file

---

admin/payments_settings.php

Enabling translation of payments settings page

l10n - payments settings

---

admin/backup.php

Enabling translation of backup settings page

l10n - backup settings

---

admin/functions.php
admin/socialLogin_settings.php

Enabling translation of social login settings page

l10n - social login settings

---

admin/customize_settings_native.php
admin/customize_settings_plugin.php
admin/design_colors.php
admin/general_settings_encoder.php
admin/general_settings_upload.php
admin/general_settings_user.php
admin/index.php
admin/mail_all_users.php
plugin/Articles/Articles.php
plugin/Live/Live.php
view/configurations_body.php
view/managerPlugins_body.php
view/managerUsersGroups_body.php
view/managerUsers_body.php

Enabling translation parts of the system

l10n - untranslatable strings

---

.editorconfig
Dockerfile
README.md
deploy/apache/avideo.conf
docker-compose.yml
objects/aVideoEncoderNotifyIsDone.json.php
objects/aVideoEncoderReceiveImage.json.php
storage/data/.gitignore

I prepare a Docker version of the site ideal for local development.

Docker enviroment

---

objects/user.php
plugin/API/API.php

API for updating profile/background image

---

plugin/CustomizeAdvanced/CustomizeAdvanced.php

`updateDiskUsage` and `removeThumbs` buttons may be translated now.

CustomizeAdvanced: Support new strings translation

---

view/managerVideos_body.php

This PR allow some new strings to be translated in the `managerVideos_body.php` file.
Please note, this PR doesn't includes any updated locale file.

ManagerVideos: Allow strings to be translated

---

.gitignore

Linked to https://github.com/WWBN/AVideo/issues/4261.

Ignore sitemap.xml file

---

objects/aVideoEncoder.json.php
objects/aVideoEncoderNotifyIsDone.json.php

Requires https://github.com/WWBN/AVideo-Encoder/pull/338

Allow AVideo-Encoder to specify the desired video status

---

Dockerfile

chown: cannot access '/var/www/avideo/videos': No such file or directory fix

chown: No such file or directory fix

---

objects/aVideoQueueEncoder.json.php

These where added in AVideo-Encoder, but AVideo does not know about
them yet.

Add support for the webm, status_override, and update_video_id fields

---

plugin/YPTSocket/YPTSocket.php

https://github.com/WWBN/AVideo/issues/4787

fix websocket @reboot issue

---

locale/pt_BR.php

I'm walking through the code and translating everything I can, hope you don't mind.

login page missing translation phrases

---

locale/pt_BR.php
view/include/blockedUser.php
view/include/offlinePage.php

Based on view/include/navbar.php file

More language updates

---

index.php
locale/pt_BR.php

added translations strings into index.php main AVideo file

index.php main file translations strings

---

locale/pt_BR.php
objects/aVideoEncoder.json.php
objects/aVideoEncoderNotifyIsDone.json.php
objects/aVideoEncoderReceiveImage.json.php
objects/youtubeUpload.json.php
view/configurations_body.php
view/modeYoutubeBottom.php

Using a simple scrtipt crawling throughout the code, all translation strings available were indexed, removed the vaste majority of duplicated translation strings.

All translation strings added to pt_BR.php

---

objects/security.php

Best to avoid eval() whenever using it isn't strictly necessary.

Avoid eval().

---

locale/pt_BR.php
plugin/PlayLists/Objects/Playlists_schedules.php
plugin/PlayLists/View/Playlists_schedules/index_body.php
plugin/YPTWallet/view/adminManageWallets.php
view/configurations_body.php
view/error.php

All translation strings found in the master code were translated. Some code receive an update because some mistypo found.

pt-br translation finished

---

locale/pt_BR.php
plugin/PlayLists/PlayLists.php

fixed translation strings in 3 functions inside PlayLists plugin class

PlayLists translation strings applied

---

plugin/WWBN/page/info.php
plugin/WWBN/page/wwbn_signup.php

Update video links & website link

---

plugin/DiscordNotify/DiscordNotify.php

This PR fixes the DiscordNotify plugin

Update DiscordNotify plugin

---

README.md

Update PHP 5.6 requirement button to PHP 7.3 requirement button.

README.md patch.

---

.htaccess
objects/functions.php

Added a cleanup of 2 strings that was found in YouTube Videos

---

.github/workflows/docker-image.yml
.github/workflows/validate.yml

Bump actions/checkout from v2 to v3.

Workflows patch.

---

view/managerVideosLight_meta.php

When uploading a photo in article, an error happens. This solved it for me

Fix bug videos_id undefined

---

.github/dependabot.yml

Included npm in the dependabot config

chore: Included npm in the dependabot config

---

view/js/script.js

Replacing a space with a space: Won't do anything, so not needed.

Remove redundant line.

---

plugin/WWBNIndex/WWBNIndex.php

sorry, missed out in last update

changed dev4.youportal.com url to wwbn.com

---

plugin/WWBNIndex/ajax.php
plugin/WWBNIndex/submitIndex.php

update condition to prevent host to be indexed if not https/accessible public

Update for WWBNIndex Plugin

---

view/help.php

This commit fixes an outdated link in the help.php file.

Fix outdated link.
